<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WordPress Image URL Generator</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        #url-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 30px;
            max-width: 900px;
            margin: 0 auto;
        }
        .url-box {
            width: 100%;
            background: white;
            padding: 20px;
            box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            position: relative;
        }
        label {
            font-size: 18px;
            margin-bottom: 10px;
            display: inline-block;
            font-weight: bold;
            color: #333;
        }
        input[type="text"] {
            width: calc(100% - 20px);
            padding: 8px 10px;
            font-size: 16px;
            margin-bottom: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            outline: none;
        }
        .button-container {
            display: flex;
            justify-content: center;
            gap: 10px;
        }
        button {
            padding: 10px 20px;
            font-size: 16px;
            color: white;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s, transform 0.1s ease-in-out;
        }
        button:disabled {
            background-color: #cccccc;
        }
        button:hover {
            background-color: #0056b3;
        }
        button:active {
            transform: scale(0.98);
        }
        .clear-button {
            background-color: #ff4d4d;
        }
        .preview-container {
            margin-top: 15px;
            display: none;
            justify-content: center;
            align-items: center;
        }
        .preview-container img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }
        .copy-image-tag-button {
            background-color: #28a745; /* Green */
        }
        .copy-image-tag-button:hover {
            background-color: #218838; /* Darker green */
        }
    </style>
<script type="text/javascript">
  function passwordProtect() {
    var password = prompt("Enter the password:");
    if (password !== "password") {
      alert("Incorrect password.");
      window.location.href = "error.html"; // Redirects to an error page or home page
    }
  }
</script>
</head>
<body onload="passwordProtect()">
  <!-- Your content goes here -->
  <h1>Protected Content</h1>
  <p>This content is password-protected.</p>
    <div id="url-container">
        <!-- URL Input Box 1 -->
        <div class="url-box">
            <label for="user-url-1">Enter URL 1:</label>
            <input type="text" id="user-url-1" placeholder="https://example.com" oninput="modifyURL(1)">
            <input type="text" id="modified-url-1" readonly>
            <div class="button-container">
                <button onclick="pasteFromClipboard(1)">Paste from Clipboard</button>
                <button onclick="copyToClipboard(1)" id="copy-button-1" disabled>Copy URL</button>
                <button onclick="clearInput(1)" class="clear-button" id="clear-button-1">Clear</button>
                <button onclick="copyImageTag(1)" id="copy-image-tag-button-1" disabled class="copy-image-tag-button">Copy Image Tag</button>
            </div>
            <div id="preview-container-1" class="preview-container">
                <img id="image-preview-1" src="" alt="Image Preview 1">
            </div>
        </div>

        <!-- URL Input Box 2 -->
        <div class="url-box">
            <label for="user-url-2">Enter URL 2:</label>
            <input type="text" id="user-url-2" placeholder="https://example.com" oninput="modifyURL(2)">
            <input type="text" id="modified-url-2" readonly>
            <div class="button-container">
                <button onclick="pasteFromClipboard(2)">Paste from Clipboard</button>
                <button onclick="copyToClipboard(2)" id="copy-button-2" disabled>Copy URL</button>
                <button onclick="clearInput(2)" class="clear-button" id="clear-button-2">Clear</button>
                <button onclick="copyImageTag(2)" id="copy-image-tag-button-2" disabled class="copy-image-tag-button">Copy Image Tag</button>
            </div>
            <div id="preview-container-2" class="preview-container">
                <img id="image-preview-2" src="" alt="Image Preview 2">
            </div>
        </div>

        <!-- URL Input Box 3 -->
        <div class="url-box">
            <label for="user-url-3">Enter URL 3:</label>
            <input type="text" id="user-url-3" placeholder="https://example.com" oninput="modifyURL(3)">
            <input type="text" id="modified-url-3" readonly>
            <div class="button-container">
                <button onclick="pasteFromClipboard(3)">Paste from Clipboard</button>
                <button onclick="copyToClipboard(3)" id="copy-button-3" disabled>Copy URL</button>
                <button onclick="clearInput(3)" class="clear-button" id="clear-button-3">Clear</button>
                <button onclick="copyImageTag(3)" id="copy-image-tag-button-3" disabled class="copy-image-tag-button">Copy Image Tag</button>
            </div>
            <div id="preview-container-3" class="preview-container">
                <img id="image-preview-3" src="" alt="Image Preview 3">
            </div>
        </div>
    </div>

    <script>
        function modifyURL(index) {
            var userUrl = document.getElementById("user-url-" + index).value;
            if (!userUrl.includes("https://")) {
                return;
            }
            var modifiedUrl = userUrl.replace("https://", "https://i0.wp.com/");
            document.getElementById("modified-url-" + index).value = modifiedUrl;
            document.getElementById("copy-button-" + index).disabled = false;
            document.getElementById("copy-image-tag-button-" + index).disabled = false; // Enable Copy Image Tag button
            previewImage(modifiedUrl, index);
        }
    </script>

    <script>
        function clearInput(index) {
            document.getElementById("user-url-" + index).value = "";
            document.getElementById("modified-url-" + index).value = "";
            document.getElementById("copy-button-" + index).disabled = true;
            document.getElementById("copy-image-tag-button-" + index).disabled = true; // Disable Copy Image Tag button
            document.getElementById("preview-container-" + index).style.display = "none"; // Hide image preview
        }
    </script>

    <script>
        function copyToClipboard(index) {
            var modifiedUrl = document.getElementById("modified-url-" + index).value;
            navigator.clipboard.writeText(modifiedUrl).catch(function(err) {
                console.error("Failed to copy URL:", err);
            });
        }
    </script>

    <script>
        function pasteFromClipboard(index) {
            navigator.clipboard.readText().then(function(text) {
                document.getElementById("user-url-" + index).value = text;
                modifyURL(index);
            }).catch(function(err) {
                console.error("Failed to read clipboard contents:", err);
            });
        }
    </script>

    <script>
        function previewImage(url, index) {
            var previewContainer = document.getElementById("preview-container-" + index);
            var imgElement = document.getElementById("image-preview-" + index);
            imgElement.src = url;
            imgElement.onload = function() {
                previewContainer.style.display = "flex"; // Show the image preview
            };
        }
    </script>

    <script>
        function copyImageTag(index) {
            var modifiedUrl = document.getElementById("modified-url-" + index).value;
            var img = new Image();
            img.src = modifiedUrl;

            img.onload = function() {
                var imageTag = `<img class="aligncenter" src="${modifiedUrl}" width="${img.width}" height="${img.height}" />`;
                navigator.clipboard.writeText(imageTag).catch(function(err) {
                    console.error("Failed to copy image tag:", err);
                });
            };
        }
    </script>
</body>
</html>
